### ISSUE TITLE
[question] Conditional task execution

### ISSUE THREAD

**Issue by sesm** [TomerAberbach/grfn#2]
First of all, thanks for the lib, looks great!

I have a question: what if I have `task A`, and based on result of `task A` I need to execute either `task B` or `task C`? So that in the end one of `B` and `C` needs to be executed, but not both of them.

**Comment by TomerAberbach** [comment]
Great question!

I'd say it depends. If the dependents of `taskB` and `taskC` are the same (meaning that the only difference in the graph is choosing either `taskB` or `taskC`, but everything else in the graph stays the same), then I would just use a normal conditional:
```js
function taskBOrC(a) {
  return checkSomeCondition(a) ? taskB(a) : taskC(a)
}
``` 
And have `taskBOrC` depend on `taskA`. `checkSomeCondition` could be asynchronous if necessary.

Otherwise, if you expect the dependents of `taskB` and `taskC` to be completely different (but join up again at some other vertex), then I would make a separate `grfn` graph for each and again use a conditional:
```js
const runTasksInvolvingB = grfn(...)
const runTasksInvolvingC = grfn(...)

function taskBOrC(a) {
  return checkSomeCondition(a) ? runTasksInvolvingB(a) : runTasksInvolvingC(a)
}
```

You could also dynamically create "inner" graph(s) if you need to:
```js
function taskBOrC(a) {
  const runInnerTasks = grfn(
    checkSomeCondition(a)
      ? [...] // Some graph related to taskA output and taskB
      : [...] // Some graph related to taskA output and taskC
  )

  return runInnerTasks(a)
}
```

Hope that helps!

**Comment by sesm** [comment]
Thanks for comprehensive answer!
